os: linux
language: python

sudo: true
python: 3.6

services:
  - docker

install:
  - travis/install-nodejs.sh
  - pip install -r travis/requirements.txt

before_script:
  - pip freeze
  - pwd

script:
  - bash travis/conformance-tests.sh
  - bash tests/cwltest.sh
