sudo: true
language: python
python: 3.6

services:
  - docker

env:
  - TOOL="Validate tools" SCRIPT="travis/tools-validation-tests.sh"
  - TOOL="Diamond blastX" TEST="tools/Diamond/Diamon_blastx_test.yml"
  - TOOL="Diamond blastP" TEST="tools/Diamond/Diamon_blastp_test.yml"
#  - TOOL="Tool validation tests" SCRIPT="travis/tools-validation-tests.sh"
#  -
#  - TOOL="Workflow validation tests" SCRIPT="travis/workflow-cwl-validation-tests.sh"
#  - TOOL="Utils validation tests" SCRIPT="travis/utils-validation-tests.sh"

install:
  - travis/install-nodejs.sh
  - pip install -r travis/requirements.txt

script:
  - if [$TOOL=="Validate tools"]; then
      bash $SCRIPT;
    else
      cwltest --verbose --test $TEST;
    fi

#    - language: Python
#      python: 3.6
#      os: linux
#      env: TOOL=Diamond.blastx-v0.9.21
#      services:
#        - docker
#      install:
#        - travis/install-nodejs.sh
#        - pip install -r travis/requirements.txt
#      script:
#        - bash travis/run-diamond.blastx-v0.9.21.sh
#        - if ! [ -e tools/Diamond/test_transcripts.fasta.diamond_matches ]; then exit 1; fi
#        - if ! diff -q tools/Diamond/test_transcripts.fasta.diamond_matches tools/Diamond/expected_output/test_transcripts.fasta.diamond_matches &>/dev/null; then exit 1; fi
#
#    - language: Python
#      python: 3.6
#      os: linux
#      env: TOOL=Diamond.blastp-v0.9.21
#      services:
#        - docker
#      install:
#        - travis/install-nodejs.sh
#        - pip install -r travis/requirements.txt
#      script:
#        - bash travis/run-diamond.blastp-v0.9.21.sh
#        - if ! [ -e tools/Diamond/test_proteins.faa.diamond_matches ]; then exit 1; fi
#        - if ! diff -q tools/Diamond/test_proteins.faa.diamond_matches tools/Diamond/expected_output/test_proteins.faa.diamond_matches &>/dev/null; then exit 1; fi
#

#install:
#  - echo "Installing"
#  - pip install -r requirements.txt
#  - pip install -r requirements-test.txt
  # Build any required docker containers here
# - docker build -t mgnify/pipeline-v5-container_name <path>

#script:
#  - echo "Test"
#  - cwltest --test $TRAVIS_BUID_DIR/test_workflow.yml  --verbose

#deploy:
#  provider: script
#  script: bash $TRAVOS_BUILD_DIR/docker_push.sh
#  on:
#    branch: master
#    os: linux