os: linux

sudo: true
language: python
python: 3.6
services:
  - docker

env:
  - TOOL="Validate" CONF_SCRIPT="travis/conformance-tests.sh"

install:
  - travis/install-nodejs.sh
  - pip install -r travis/requirements.txt

before_script:
  - pip freeze
  - pwd

script:
  - bash ${CONF_SCRIPT}
