sudo: true
language: python
python: 3.6

services:
  - docker

env:
  - TOOL="Validate tools" SCRIPT="travis/tools-validation-tests.sh"
  - TOOL="Validate tools" SCRIPT="travis/utils-validation-tests.sh"
  - TOOL="Diamond blastX" TEST="tools/Diamond/Diamond_blastx_test.yml"
  - TOOL="Diamond blastP" TEST="tools/Diamond/Diamond_blastp_test.yml"
  - TOOL="Diamond Post Processing Sorting" TEST="tools/Diamond-Post-Processing/diamond_sorting.test.yaml"
  - TOOL="Diamond Post Processing Joining" TEST="tools/Diamond-Post-Processing/diamond_join.test.yaml"
  - TOOL="Diamond Post Processing workflow" TEST="tools/Diamond-Post-Processing/postprocessing_pipeline.test.yml"
#  - TOOL="Workflow validation tests" SCRIPT="travis/workflow-cwl-validation-tests.sh"
#  - TOOL="Utils validation tests" SCRIPT="travis/utils-validation-tests.sh"

install:
  - travis/install-nodejs.sh
  - pip install -r travis/requirements.txt

script:
  - if [ "$SCRIPT" ]; then
      bash $SCRIPT;
    else
      cwltest --verbose --test $TEST;
    fi

#install:
#  - echo "Installing"
#  - pip install -r requirements.txt
#  - pip install -r requirements-test.txt
  # Build any required docker containers here
# - docker build -t mgnify/pipeline-v5-container_name <path>

#script:
#  - echo "Test"
#  - cwltest --test $TRAVIS_BUID_DIR/test_workflow.yml  --verbose

#deploy:
#  provider: script
#  script: bash $TRAVOS_BUILD_DIR/docker_push.sh
#  on:
#    branch: master
#    os: linux