#!/bin/bash

while getopts i:o: option; do
	case "${option}" in
		i) INPUT=${OPTARG};;
		o) OUTPUT=${OPTARG};;
	esac
done

echo ";var fs = require('fs'); fs.writeFileSync('${OUTPUT}', JSON.stringify(geneclusters));" >> ${INPUT} && \
node ${INPUT}