FROM perl:latest

COPY esl-ssplit.pl /

#RUN chmod -R a+rwx /tools
#ENV PATH="/tools:${PATH}"

##############################################################
# Dockerfile Version:   19.03.1
# Software:             esl-ssplit.pl
# Software Version:     1.0.0
# Description:          Chunking DNA files
##############################################################


CMD ["esl-ssplit.pl"]