FROM python:3

LABEL maintainer="Ekaterina Sakharova <kates@ebi.ac.uk>"


##############################################################
# Dockerfile Version:   18.06.0-ce
# Software:             union_by_contigs.py
# Software Version:     1.0.0
##############################################################
COPY union_by_contigs.py /union_by_contigs.py


CMD ["python", "/union_by_contigs.py"]