FROM perl:latest

COPY mapseq2biom.pl /

##############################################################
# Dockerfile Version:   19.03.1
# Software:             mapseq2biom.py
# Software Version:     1.0.0
# Description:          Convert mapseq to OTU tsv format for krona
##############################################################


CMD ["perl", "/mapseq2biom.pl"]