os: linux
language: python

sudo: true
python: 3.6

services:
  - docker

install:
  - install-nodejs.sh
  - pip install -r requirements.txt

before_script:
  - pip freeze
  - pwd

script:
  - bash ../tests/conformance-tests/conformance-tests.sh
  # disabled, travis VM has only 1 core- bash tests/cwltest.sh
