#!/usr/bin/env bash

coordinates=$1
stats=$2
fasta=$3


y=($( wc -l $coordinates))
x=($(grep -m1 "sequence_count" $stats | cut -f 2))

proportion=($(bc <<< "scale=10; ($y/$x)"))
num1=0.9

standard=$((`echo "$proportion >= $num1"| bc`))
if [ $standard -eq 1 ]
then
  #mv "$fasta" "Empty.fasta"
  touch "Empty.fasta"
else
  cp "$fasta" "$fasta.not_empty.fasta"
fi

###