#!/usr/bin/env bash

coordinates_LSU=$1
coordinates_SSU=$2
stats=$3
fasta=$4

coordinates=($( cat $coordinates_LSU $coordinates_LSU ))

y=($( grep ">" $coordinates | wc -l ))
x=($(grep -m1 "sequence_count" $stats | cut -f 2))

proportion=($(bc <<< "scale=10; ($y/$x)"))
num1=0.9

standard=$((`echo "$proportion >= $num1"| bc`))
if [ $standard -eq 1 ]
then
  mv "$fasta" "EMPTY.fasta"
else
  cp "$fasta" .
fi

###